sudo: false
language: ruby

cache:
  bundler: true

rvm:
  - 2.1 # tests on latest 2.1.x
  - 2.2.5 # tests on latest 2.2.x
  - 2.3.1

install:
  - gem install bundler:1.17.3
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
